# Generated by Django 4.0.1 on 2022-01-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
    ]
